export class DashboardGaranzieScadenzaChart {
    settimane: any;
    constructor(
        public giorno_1?: number,
        public giorno_2?: number,
        public giorno_3?: number,
        public giorno_4?: number,
        public giorno_5?: number,
        public giorno_6?: number,
        public giorno_7?: number,
        public giorno_8?: number,
        public giorno_9?: number,
        public giorno_10?: number,
        public giorno_11?: number,
        public giorno_12?: number,
        public giorno_13?: number,
        public giorno_14?: number,
        public giorno_15?: number,
        public giorno_16?: number,
        public giorno_17?: number,
        public giorno_18?: number,
        public giorno_19?: number,
        public giorno_20?: number,
        public giorno_21?: number,
        public giorno_22?: number,
        public giorno_23?: number,
        public giorno_24?: number,
        public giorno_25?: number,
        public giorno_26?: number,
        public giorno_27?: number,
        public giorno_28?: number,
        public giorno_29?: number,
        public giorno_30?: number,
        public giorno_31?: number,
        public maxValue?: number,
        public lastDate?: Date
    ) { }
}